Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dict1=dict()
        # check all chars in s
        for i in s:
            dict1[i]=dict1.get(i,0)+1
        for j in t:
            if j in dict1:
                dict1[j]=dict1[j]-1
                if dict1[j]==0:
                    del dict1[j]
            else:
                return j
